version: 2
updates:
    - package-ecosystem: "bun"
      directory: "/"
      target-branch: "main"
      open-pull-requests-limit: 10
      schedule:
          timezone: "Europe/Warsaw"
          interval: "weekly"
      commit-message:
          prefix: "chore(deps->root):"
      labels: ["🔄 dependencies"]

    - package-ecosystem: "bun"
      directory: "/packages/themes"
      target-branch: "main"
      open-pull-requests-limit: 10
      schedule:
          timezone: "Europe/Warsaw"
          interval: "weekly"
      commit-message:
          prefix: "chore(deps->themes):"
      labels: ["🔄 dependencies"]

    - package-ecosystem: "bun"
      directory: "/apps/docs"
      target-branch: "main"
      open-pull-requests-limit: 10
      schedule:
          timezone: "Europe/Warsaw"
          interval: "weekly"
      commit-message:
          prefix: "chore(deps->docs):"
      labels: ["🔄 dependencies"]

    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: "main"
      open-pull-requests-limit: 10
      schedule:
          timezone: "Europe/Warsaw"
          interval: "weekly"
      commit-message:
          prefix: "chore(deps->actions):"
      labels: ["🔄 dependencies"]
