import { defineConfig } from "bunup";

export default defineConfig({
	entry: [
		"src/index.ts",
		"src/client.ts",
		"src/client/use-theme.ts",
		"src/client/use-theme-value.ts",
		"src/client/use-theme-effect.ts",
		"src/client/use-hydrated.ts",
		"src/client/themed-image.ts",
		"src/client/provider.ts",
		"src/client/create-themes.ts",
		"src/next.ts",
		"src/script.ts",
		"src/providers/client-next-provider.tsx",
	],
	format: ["esm"],
	splitting: true,
	target: "browser",
	sourceBase: "./src",
	dts: {
		entry: [
			"src/index.ts",
			"src/client.ts",
			"src/client/use-theme.ts",
			"src/client/use-theme-value.ts",
			"src/client/use-theme-effect.ts",
			"src/client/use-hydrated.ts",
			"src/client/themed-image.ts",
			"src/client/provider.ts",
			"src/client/create-themes.ts",
			"src/next.ts",
			"src/script.ts",
		],
		splitting: true,
	},
	external: ["next/headers"],
	env: { NODE_ENV: "production" },
});
